from otree.api import Currency as c, currency_range
from . import views
from ._builtin import Bot
from .models import Constants

class PlayerBot(Bot):
    cases = ["one_player_all_no",
            "one_player_all_yes",
            "fifteen_players_all_no",
            "fifteen_players_all_yes",
            "fifteen_players_mix",]
    def play_round(self):
        yield (views.AssignAvatar)
        for d in range(Constants.num_messaging_rounds):
            yield (views.Discuss)
        if self.session.num_participants == 1:
            if self.case == "one_player_all_no":
                yield (views.Decide, {"participate": False})
                assert self.player.round_payoff == 50
            elif self.case == "one_player_all_yes":
                yield (views.Decide, {"participate": True})
                assert self.player.round_payoff != 50
            else:
                yield (views.Decide, {"participate": True})
        elif self.session.num_participants == 15:
            if self.case == "fifteen_players_all_no":
                yield (views.Decide, {"participate": False})
                assert self.player.round_payoff == 50
            elif self.case == "fifteen_players_all_yes":
                yield (views.Decide, {"participate": True})
                assert self.player.round_payoff == 100
            elif self.case == "fifteen_players_mix":
                if (self.participant.id_in_session == 1 or
                        self.participant.id_in_session == 3 or
                        self.participant.id_in_session == 5 or
                        self.participant.id_in_session == 7 or
                        self.participant.id_in_session == 9 or
                        self.participant.id_in_session == 11 or
                        self.participant.id_in_session == 13 or
                        self.participant.id_in_session == 15):
                    yield (views.Decide, {"participate": True})
                elif (self.participant.id_in_session == 2 or
                        self.participant.id_in_session == 4 or
                        self.participant.id_in_session == 6 or
                        self.participant.id_in_session == 8 or
                        self.participant.id_in_session == 10 or
                        self.participant.id_in_session == 12 or
                        self.participant.id_in_session == 14):
                    yield (views.Decide, {"participate": False})
                if self.subsession.round_number == 1:
                    if self.participant.id_in_session == 1:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 2:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 3:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 4:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 5:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 6:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 7:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 8:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 9:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 10:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 11:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 12:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 13:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 14:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 15:
                        assert self.player.round_payoff == 0
                if self.subsession.round_number == 2:
                    if self.participant.id_in_session == 1:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 2:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 3:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 4:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 5:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 6:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 7:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 8:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 9:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 10:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 11:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 12:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 13:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 14:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 15:
                        assert self.player.round_payoff == 100
                if self.subsession.round_number == 3:
                    if self.participant.id_in_session == 1:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 2:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 3:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 4:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 5:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 6:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 7:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 8:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 9:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 10:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 11:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 12:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 13:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 14:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 15:
                        assert self.player.round_payoff == 100
                if self.subsession.round_number == 4:
                    if self.participant.id_in_session == 1:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 2:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 3:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 4:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 5:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 6:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 7:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 8:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 9:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 10:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 11:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 12:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 13:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 14:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 15:
                        assert self.player.round_payoff == 0
                if self.subsession.round_number == 5:
                    if self.participant.id_in_session == 1:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 2:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 3:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 4:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 5:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 6:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 7:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 8:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 9:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 10:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 11:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 12:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 13:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 14:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 15:
                        assert self.player.round_payoff == 100
                if self.subsession.round_number == 6:
                    if self.participant.id_in_session == 1:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 2:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 3:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 4:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 5:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 6:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 7:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 8:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 9:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 10:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 11:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 12:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 13:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 14:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 15:
                        assert self.player.round_payoff == 100
                if self.subsession.round_number == 7:
                    if self.participant.id_in_session == 1:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 2:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 3:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 4:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 5:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 6:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 7:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 8:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 9:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 10:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 11:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 12:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 13:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 14:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 15:
                        assert self.player.round_payoff == 100
                if self.subsession.round_number == 8:
                    if self.participant.id_in_session == 1:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 2:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 3:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 4:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 5:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 6:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 7:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 8:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 9:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 10:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 11:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 12:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 13:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 14:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 15:
                        assert self.player.round_payoff == 0
                if self.subsession.round_number == 9:
                    if self.participant.id_in_session == 1:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 2:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 3:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 4:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 5:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 6:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 7:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 8:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 9:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 10:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 11:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 12:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 13:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 14:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 15:
                        assert self.player.round_payoff == 100
                if self.subsession.round_number == 10:
                    if self.participant.id_in_session == 1:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 2:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 3:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 4:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 5:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 6:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 7:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 8:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 9:
                        assert self.player.round_payoff == 0
                    if self.participant.id_in_session == 10:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 11:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 12:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 13:
                        assert self.player.round_payoff == 100
                    if self.participant.id_in_session == 14:
                        assert self.player.round_payoff == 50
                    if self.participant.id_in_session == 15:
                        assert self.player.round_payoff == 0
            else:
                yield (views.Decide, {"participate": True})
                    
